// <auto-generated />
using System;
using LuuKyCanTin.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuuKyCanTin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003144240_AddUserOfficer")]
    partial class AddUserOfficer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Vietnamese_CI_AI")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NewValues")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("OldValues")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Workstation")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TableName", "RecordId");

                    b.ToTable("AuditLog", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_Action", "[Action] IN ('Them', 'Sua', 'Huy', 'In', 'Duyet', 'DangNhap')");
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.FacilityInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("ParentAgencyName")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("FacilityInfo", null, t =>
                        {
                            t.HasCheckConstraint("CK_FacilityInfo_Id", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = 0,
                            FacilityName = "",
                            RowVer = new byte[0]
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HT.Xem",
                            Module = "HT",
                            Name = "Xem — Hệ thống"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HT.Them",
                            Module = "HT",
                            Name = "Them — Hệ thống"
                        },
                        new
                        {
                            Id = 3,
                            Code = "HT.Sua",
                            Module = "HT",
                            Name = "Sua — Hệ thống"
                        },
                        new
                        {
                            Id = 4,
                            Code = "HT.Huy",
                            Module = "HT",
                            Name = "Huy — Hệ thống"
                        },
                        new
                        {
                            Id = 5,
                            Code = "HT.In",
                            Module = "HT",
                            Name = "In — Hệ thống"
                        },
                        new
                        {
                            Id = 6,
                            Code = "HT.Duyet",
                            Module = "HT",
                            Name = "Duyet — Hệ thống"
                        },
                        new
                        {
                            Id = 7,
                            Code = "DM.Xem",
                            Module = "DM",
                            Name = "Xem — Danh mục"
                        },
                        new
                        {
                            Id = 8,
                            Code = "DM.Them",
                            Module = "DM",
                            Name = "Them — Danh mục"
                        },
                        new
                        {
                            Id = 9,
                            Code = "DM.Sua",
                            Module = "DM",
                            Name = "Sua — Danh mục"
                        },
                        new
                        {
                            Id = 10,
                            Code = "DM.Huy",
                            Module = "DM",
                            Name = "Huy — Danh mục"
                        },
                        new
                        {
                            Id = 11,
                            Code = "DM.In",
                            Module = "DM",
                            Name = "In — Danh mục"
                        },
                        new
                        {
                            Id = 12,
                            Code = "DM.Duyet",
                            Module = "DM",
                            Name = "Duyet — Danh mục"
                        },
                        new
                        {
                            Id = 13,
                            Code = "LK-T.Xem",
                            Module = "LK-T",
                            Name = "Xem — Tăng tiền lưu ký"
                        },
                        new
                        {
                            Id = 14,
                            Code = "LK-T.Them",
                            Module = "LK-T",
                            Name = "Them — Tăng tiền lưu ký"
                        },
                        new
                        {
                            Id = 15,
                            Code = "LK-T.Sua",
                            Module = "LK-T",
                            Name = "Sua — Tăng tiền lưu ký"
                        },
                        new
                        {
                            Id = 16,
                            Code = "LK-T.Huy",
                            Module = "LK-T",
                            Name = "Huy — Tăng tiền lưu ký"
                        },
                        new
                        {
                            Id = 17,
                            Code = "LK-T.In",
                            Module = "LK-T",
                            Name = "In — Tăng tiền lưu ký"
                        },
                        new
                        {
                            Id = 18,
                            Code = "LK-T.Duyet",
                            Module = "LK-T",
                            Name = "Duyet — Tăng tiền lưu ký"
                        },
                        new
                        {
                            Id = 19,
                            Code = "LK-C.Xem",
                            Module = "LK-C",
                            Name = "Xem — Giảm tiền lưu ký"
                        },
                        new
                        {
                            Id = 20,
                            Code = "LK-C.Them",
                            Module = "LK-C",
                            Name = "Them — Giảm tiền lưu ký"
                        },
                        new
                        {
                            Id = 21,
                            Code = "LK-C.Sua",
                            Module = "LK-C",
                            Name = "Sua — Giảm tiền lưu ký"
                        },
                        new
                        {
                            Id = 22,
                            Code = "LK-C.Huy",
                            Module = "LK-C",
                            Name = "Huy — Giảm tiền lưu ký"
                        },
                        new
                        {
                            Id = 23,
                            Code = "LK-C.In",
                            Module = "LK-C",
                            Name = "In — Giảm tiền lưu ký"
                        },
                        new
                        {
                            Id = 24,
                            Code = "LK-C.Duyet",
                            Module = "LK-C",
                            Name = "Duyet — Giảm tiền lưu ký"
                        },
                        new
                        {
                            Id = 25,
                            Code = "LK-BC.Xem",
                            Module = "LK-BC",
                            Name = "Xem — Báo cáo lưu ký"
                        },
                        new
                        {
                            Id = 26,
                            Code = "LK-BC.Them",
                            Module = "LK-BC",
                            Name = "Them — Báo cáo lưu ký"
                        },
                        new
                        {
                            Id = 27,
                            Code = "LK-BC.Sua",
                            Module = "LK-BC",
                            Name = "Sua — Báo cáo lưu ký"
                        },
                        new
                        {
                            Id = 28,
                            Code = "LK-BC.Huy",
                            Module = "LK-BC",
                            Name = "Huy — Báo cáo lưu ký"
                        },
                        new
                        {
                            Id = 29,
                            Code = "LK-BC.In",
                            Module = "LK-BC",
                            Name = "In — Báo cáo lưu ký"
                        },
                        new
                        {
                            Id = 30,
                            Code = "LK-BC.Duyet",
                            Module = "LK-BC",
                            Name = "Duyet — Báo cáo lưu ký"
                        },
                        new
                        {
                            Id = 31,
                            Code = "NH.Xem",
                            Module = "NH",
                            Name = "Xem — Nhập hàng"
                        },
                        new
                        {
                            Id = 32,
                            Code = "NH.Them",
                            Module = "NH",
                            Name = "Them — Nhập hàng"
                        },
                        new
                        {
                            Id = 33,
                            Code = "NH.Sua",
                            Module = "NH",
                            Name = "Sua — Nhập hàng"
                        },
                        new
                        {
                            Id = 34,
                            Code = "NH.Huy",
                            Module = "NH",
                            Name = "Huy — Nhập hàng"
                        },
                        new
                        {
                            Id = 35,
                            Code = "NH.In",
                            Module = "NH",
                            Name = "In — Nhập hàng"
                        },
                        new
                        {
                            Id = 36,
                            Code = "NH.Duyet",
                            Module = "NH",
                            Name = "Duyet — Nhập hàng"
                        },
                        new
                        {
                            Id = 37,
                            Code = "BH.Xem",
                            Module = "BH",
                            Name = "Xem — Bán hàng"
                        },
                        new
                        {
                            Id = 38,
                            Code = "BH.Them",
                            Module = "BH",
                            Name = "Them — Bán hàng"
                        },
                        new
                        {
                            Id = 39,
                            Code = "BH.Sua",
                            Module = "BH",
                            Name = "Sua — Bán hàng"
                        },
                        new
                        {
                            Id = 40,
                            Code = "BH.Huy",
                            Module = "BH",
                            Name = "Huy — Bán hàng"
                        },
                        new
                        {
                            Id = 41,
                            Code = "BH.In",
                            Module = "BH",
                            Name = "In — Bán hàng"
                        },
                        new
                        {
                            Id = 42,
                            Code = "BH.Duyet",
                            Module = "BH",
                            Name = "Duyet — Bán hàng"
                        },
                        new
                        {
                            Id = 43,
                            Code = "HH-BC.Xem",
                            Module = "HH-BC",
                            Name = "Xem — Báo cáo hàng hóa"
                        },
                        new
                        {
                            Id = 44,
                            Code = "HH-BC.Them",
                            Module = "HH-BC",
                            Name = "Them — Báo cáo hàng hóa"
                        },
                        new
                        {
                            Id = 45,
                            Code = "HH-BC.Sua",
                            Module = "HH-BC",
                            Name = "Sua — Báo cáo hàng hóa"
                        },
                        new
                        {
                            Id = 46,
                            Code = "HH-BC.Huy",
                            Module = "HH-BC",
                            Name = "Huy — Báo cáo hàng hóa"
                        },
                        new
                        {
                            Id = 47,
                            Code = "HH-BC.In",
                            Module = "HH-BC",
                            Name = "In — Báo cáo hàng hóa"
                        },
                        new
                        {
                            Id = 48,
                            Code = "HH-BC.Duyet",
                            Module = "HH-BC",
                            Name = "Duyet — Báo cáo hàng hóa"
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "QUAN_TRI",
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = 0,
                            Name = "Quản trị hệ thống",
                            RowVer = new byte[0]
                        },
                        new
                        {
                            Id = 2,
                            Code = "LUU_KY",
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = 0,
                            Name = "Cán bộ theo dõi tiền lưu ký",
                            RowVer = new byte[0]
                        },
                        new
                        {
                            Id = 3,
                            Code = "CAN_TIN",
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = 0,
                            Name = "Cán bộ căn tin / bán hàng",
                            RowVer = new byte[0]
                        },
                        new
                        {
                            Id = 4,
                            Code = "QUAN_GIAO",
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = 0,
                            Name = "Cán bộ quản giáo",
                            RowVer = new byte[0]
                        },
                        new
                        {
                            Id = 5,
                            Code = "LANH_DAO",
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = 0,
                            Name = "Chỉ huy phụ trách / Lãnh đạo đơn vị",
                            RowVer = new byte[0]
                        },
                        new
                        {
                            Id = 6,
                            Code = "KE_TOAN",
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = 0,
                            Name = "Kế toán đơn vị",
                            RowVer = new byte[0]
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 38
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 39
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 40
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 44
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 45
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 46
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 47
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 48
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 43
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<byte>("FailedAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LockedUntil")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("OfficerId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OfficerId")
                        .IsUnique()
                        .HasDatabaseName("UX_User_OfficerId_IsActive")
                        .HasFilter("[IsActive] = 1 AND [OfficerId] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_OfficerId", "[OfficerId] IS NOT NULL OR [UserName] = 'admin'");
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.VoucherCounter", b =>
                {
                    b.Property<string>("VoucherTypeCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.Property<int>("CurrentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("VoucherTypeCode", "Year");

                    b.ToTable("VoucherCounter", (string)null);

                    b.HasData(
                        new
                        {
                            VoucherTypeCode = "BNT",
                            Year = (short)2026,
                            CurrentNumber = 0,
                            Prefix = "BNT"
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Custody.CustodyVoucher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("AmountInWords")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("CancelledById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InmateFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InmateId")
                        .HasColumnType("int");

                    b.Property<byte>("InmateType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<short>("PrintCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateOnly?>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<string>("Relationship")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SenderAccountNumber")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SenderFullName")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceDocumentNumber")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("VoucherDate")
                        .HasColumnType("date");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte>("VoucherType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("VoucherDate")
                        .HasFilter("[Status] = 2");

                    b.HasIndex("VoucherNumber")
                        .IsUnique();

                    b.HasIndex("InmateId", "VoucherDate", "Id");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("InmateId", "VoucherDate", "Id"), new[] { "VoucherType", "Amount", "Status" });

                    b.ToTable("CustodyVoucher", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustodyVoucher_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_CustodyVoucher_BankTransfer", "[PaymentMethod] <> 2 OR [SenderAccountNumber] IS NOT NULL");

                            t.HasCheckConstraint("CK_CustodyVoucher_Cancellation", "[Status] <> 3 OR ([CancellationReason] IS NOT NULL AND [CancelledAt] IS NOT NULL AND [CancelledById] IS NOT NULL)");

                            t.HasCheckConstraint("CK_CustodyVoucher_InmateType", "[InmateType] IN (1, 2)");

                            t.HasCheckConstraint("CK_CustodyVoucher_PaymentMethod", "[PaymentMethod] IN (1, 2)");

                            t.HasCheckConstraint("CK_CustodyVoucher_Status", "[Status] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_CustodyVoucher_TransactionType", "[TransactionType] IN (11, 12, 13, 14, 21, 22, 23, 24, 25)");

                            t.HasCheckConstraint("CK_CustodyVoucher_TransactionType_VoucherType", "[TransactionType] / 10 = [VoucherType]");

                            t.HasCheckConstraint("CK_CustodyVoucher_VoucherType", "[VoucherType] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.MasterData.Inmate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<short?>("BirthYear")
                        .HasColumnType("smallint");

                    b.Property<string>("Cell")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<decimal>("CustodyBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InmateCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte>("InmateType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("InmateCode")
                        .IsUnique();

                    b.ToTable("Inmate", null, t =>
                        {
                            t.HasCheckConstraint("CK_Inmate_CustodyBalance", "[CustodyBalance] >= 0");

                            t.HasCheckConstraint("CK_Inmate_InmateType", "[InmateType] IN (1, 2)");

                            t.HasCheckConstraint("CK_Inmate_ReleaseDate", "[Status] = 1 OR [ReleaseDate] IS NOT NULL");

                            t.HasCheckConstraint("CK_Inmate_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.MasterData.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Latin1_General_100_CI_AI");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSupervisingOfficer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("OfficerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_Officer_FullName");

                    b.HasIndex("OfficerCode")
                        .IsUnique();

                    b.ToTable("Officer", (string)null);
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.RolePermission", b =>
                {
                    b.HasOne("LuuKyCanTin.Domain.Administration.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuuKyCanTin.Domain.Administration.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.User", b =>
                {
                    b.HasOne("LuuKyCanTin.Domain.MasterData.Officer", null)
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Administration.UserRole", b =>
                {
                    b.HasOne("LuuKyCanTin.Domain.Administration.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuuKyCanTin.Domain.Administration.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.Custody.CustodyVoucher", b =>
                {
                    b.HasOne("LuuKyCanTin.Domain.MasterData.Inmate", null)
                        .WithMany()
                        .HasForeignKey("InmateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
