// <auto-generated />
using System;
using LuuKyCanTin.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuuKyCanTin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Vietnamese_CI_AI")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuuKyCanTin.Domain.DanhMuc.DoiTuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuongGiam")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("LoaiDoiTuong")
                        .HasColumnType("tinyint");

                    b.Property<string>("MaSo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<short?>("NamSinh")
                        .HasColumnType("smallint");

                    b.Property<DateOnly?>("NgayRa")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgaySua")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayTao")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateOnly>("NgayVao")
                        .HasColumnType("date");

                    b.Property<int?>("NguoiSuaId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SoDuLuuKy")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<byte>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("Id");

                    b.HasIndex("HoTen");

                    b.HasIndex("MaSo")
                        .IsUnique();

                    b.ToTable("DoiTuong", null, t =>
                        {
                            t.HasCheckConstraint("CK_DoiTuong_LoaiDoiTuong", "[LoaiDoiTuong] IN (1, 2)");

                            t.HasCheckConstraint("CK_DoiTuong_NgayRa", "[TrangThai] = 1 OR [NgayRa] IS NOT NULL");

                            t.HasCheckConstraint("CK_DoiTuong_SoDuLuuKy", "[SoDuLuuKy] >= 0");

                            t.HasCheckConstraint("CK_DoiTuong_TrangThai", "[TrangThai] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.HeThong.DemSoChungTu", b =>
                {
                    b.Property<string>("LoaiChungTu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<short>("Nam")
                        .HasColumnType("smallint");

                    b.Property<int>("SoHienTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TienTo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("LoaiChungTu", "Nam");

                    b.ToTable("DemSoChungTu", (string)null);

                    b.HasData(
                        new
                        {
                            LoaiChungTu = "BNT",
                            Nam = (short)2026,
                            SoHienTai = 0,
                            TienTo = "BNT"
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.HeThong.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("KhoaDen")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("NgaySua")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayTao")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("NguoiSuaId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("SoLanSai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.HeThong.NhatKyThaoTac", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BanGhiId")
                        .HasColumnType("bigint");

                    b.Property<string>("DuLieuCu")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuLieuMoi")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MayTram")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TenBang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ThoiDiem")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("ThoiDiem");

                    b.HasIndex("TenBang", "BanGhiId");

                    b.ToTable("NhatKyThaoTac", null, t =>
                        {
                            t.HasCheckConstraint("CK_NhatKyThaoTac_HanhDong", "[HanhDong] IN ('Them', 'Sua', 'Huy', 'In', 'Duyet', 'DangNhap')");
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.HeThong.ThongTinDonVi", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("NgaySua")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayTao")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("NguoiSuaId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenCoQuanChuQuan")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ThongTinDonVi", null, t =>
                        {
                            t.HasCheckConstraint("CK_ThongTinDonVi_Id", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChi = "",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiTaoId = 0,
                            RowVer = new byte[0],
                            TenDonVi = ""
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.LuuKy.ChungTuLuuKy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DoiTuongId")
                        .HasColumnType("int");

                    b.Property<byte>("HinhThuc")
                        .HasColumnType("tinyint");

                    b.Property<string>("HoTenDoiTuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("LoaiDoiTuong")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LoaiPhieu")
                        .HasColumnType("tinyint");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("NgayChungTu")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayHuy")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateOnly?>("NgayNhan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgaySua")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayTao")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<byte>("NghiepVu")
                        .HasColumnType("tinyint");

                    b.Property<string>("NguoiGuiHoTen")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NguoiHuyId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiSuaId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuanHe")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SoChungTu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("SoDuSau")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("SoDuTruoc")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<short>("SoLanIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("SoPhieuGoc")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SoTaiKhoanNguoiGui")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("SoTienBangChu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("NgayChungTu")
                        .HasFilter("[TrangThai] = 2");

                    b.HasIndex("SoChungTu")
                        .IsUnique();

                    b.HasIndex("DoiTuongId", "NgayChungTu", "Id");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DoiTuongId", "NgayChungTu", "Id"), new[] { "LoaiPhieu", "SoTien", "TrangThai" });

                    b.ToTable("ChungTuLuuKy", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChungTuLuuKy_ChuyenKhoan", "[HinhThuc] <> 2 OR [SoTaiKhoanNguoiGui] IS NOT NULL");

                            t.HasCheckConstraint("CK_ChungTuLuuKy_HinhThuc", "[HinhThuc] IN (1, 2)");

                            t.HasCheckConstraint("CK_ChungTuLuuKy_Huy", "[TrangThai] <> 3 OR ([LyDoHuy] IS NOT NULL AND [NgayHuy] IS NOT NULL AND [NguoiHuyId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ChungTuLuuKy_LoaiDoiTuong", "[LoaiDoiTuong] IN (1, 2)");

                            t.HasCheckConstraint("CK_ChungTuLuuKy_LoaiPhieu", "[LoaiPhieu] IN (1, 2)");

                            t.HasCheckConstraint("CK_ChungTuLuuKy_NghiepVu", "[NghiepVu] IN (11, 12, 13, 14, 21, 22, 23, 24, 25)");

                            t.HasCheckConstraint("CK_ChungTuLuuKy_NghiepVu_LoaiPhieu", "[NghiepVu] / 10 = [LoaiPhieu]");

                            t.HasCheckConstraint("CK_ChungTuLuuKy_SoTien", "[SoTien] > 0");

                            t.HasCheckConstraint("CK_ChungTuLuuKy_TrangThai", "[TrangThai] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("LuuKyCanTin.Domain.LuuKy.ChungTuLuuKy", b =>
                {
                    b.HasOne("LuuKyCanTin.Domain.DanhMuc.DoiTuong", null)
                        .WithMany()
                        .HasForeignKey("DoiTuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
